### ISSUE TITLE
Implement management command for downloading location data

### ISSUE THREAD

**Issue by SanketDG** [systers/portal#584]
## Description
After #572 gets merged, the repository will become larger by 60MB, which is not effecient.

So for downloading the GeoIP location data, one can use a manage command like:

```
python manage.py locationdata
```

This can also be integrated in the dev setup docs for beginners, and be used in the CI so that all checks are passed.

## Tasks
- [ ] Implement the management command
- [ ] Make sure the command works on every platform
- [ ] Write insructions in the installation and the setup docs
- [ ] Integrate in the CI and make sure tests are passing
- [ ] Remove the old files (especially the MMDB files)

_I'd be interested in mentoring someone formally for this PR. Please ping me on Zulip if you are relatively new here and you want to get started with your first PR!_

**Comment by sakshi1499** [comment]
@anitab-org/coding-team Anybody who wants to work on it?
